// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEsGd0uBUoi-h5mC26Rk9XRRfPJ5dHsw',
    appId: '1:1027606837746:web:233d70e70b02bd7873936b',
    messagingSenderId: '1027606837746',
    projectId: 'jurustay-app',
    authDomain: 'jurustay-app.firebaseapp.com',
    storageBucket: 'jurustay-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_NCAXO40Dr83bJJFlciULJzro4c6FGg',
    appId: '1:1027606837746:android:0711a8bab458219373936b',
    messagingSenderId: '1027606837746',
    projectId: 'jurustay-app',
    storageBucket: 'jurustay-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3QrhHBakBjVFPgZjjSrEwF9UJwJF9_9Q',
    appId: '1:1027606837746:ios:ca064a03d0a157cb73936b',
    messagingSenderId: '1027606837746',
    projectId: 'jurustay-app',
    storageBucket: 'jurustay-app.firebasestorage.app',
    iosBundleId: 'com.example.jurustayGroup14',
  );
}
